spring:
  datasource:
    url: jdbc:mysql://192.168.1.8:3306/yiibaidb?useUnicode=true&useSSL=false&serverTimezoneUTC
    username: root
    password: dev
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  type-aliases-package: com.zc.entity
  configuration:
    lazy-loading-enabled: true
    aggressive-lazy-loading: false
    map-underscore-to-camel-case: true
    use-column-label: true
  mapper-locations: classpath:/mapper/*.xml

#logging:
#  level:
#    com.zc.dao: debug
#    web: debug

server:
  port: 8081
